package com.seniorsteps.trainningcenter.model;
// Generated Oct 31, 2020 10:16:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CourseStudent generated by hbm2java
 */
@Entity
@Table(name="course_student"
    ,catalog="trainning_center"
)
public class CourseStudent  implements java.io.Serializable {


     private Integer id;
     private Course course;
     private Student student;
     private User user;
     private Double price;
     private Double discount;
     private Double paid;
     private Double rest;
     private Date registrationDate;
     private Set<Payment> payments = new HashSet<Payment>(0);

    public CourseStudent() {
    }

	
    public CourseStudent(Course course, Student student,User user) {
        this.course = course;
        this.student = student;
        this.user = user;
    }
    public CourseStudent(Course course, Student student,User user, Double price, Double discount, Double paid, Double rest, Date registrationDate, Set<Payment> payments) {
       this.course = course;
       this.student = student;
       this.user = user;
       this.price = price;
       this.discount = discount;
       this.paid = paid;
       this.rest = rest;
       this.registrationDate = registrationDate;
       this.payments = payments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="course_id", nullable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="student_id", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_app_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="price", precision=22, scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    
    @Column(name="discount", precision=22, scale=0)
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    
    @Column(name="paid", precision=22, scale=0)
    public Double getPaid() {
        return this.paid;
    }
    
    public void setPaid(Double paid) {
        this.paid = paid;
    }

    
    @Column(name="rest", precision=22, scale=0)
    public Double getRest() {
        return this.rest;
    }
    
    public void setRest(Double rest) {
        this.rest = rest;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="registration_date", length=10)
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courseStudent")
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }




}


