package com.seniorsteps.trainningcenter.model;
// Generated Oct 31, 2020 10:16:07 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CourseConstructor generated by hbm2java
 */
@Entity
@Table(name="course_constructor"
    ,catalog="trainning_center"
)
public class CourseConstructor  implements java.io.Serializable {


     private Integer id;
     private Course course;
     private Instructor instructor;

    public CourseConstructor() {
    }

    public CourseConstructor(Course course, Instructor instructor) {
       this.course = course;
       this.instructor = instructor;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_id", nullable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="instructor_id", nullable=false)
    public Instructor getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }




}


