package com.seniorsteps.trainningcenter.model;
// Generated Oct 31, 2020 10:16:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="trainning_center"
)
public class Payment  implements java.io.Serializable {


     private Integer id;
     private CourseStudent courseStudent;
     private User user;
     private Date date;
     private Double price;
     private Date restl;

    public Payment() {
    }

	
    public Payment(CourseStudent courseStudent,User user) {
        this.courseStudent = courseStudent;
        this.user = user;
    }
    public Payment(CourseStudent courseStudent,User user, Date date, Double price, Date restl) {
       this.courseStudent = courseStudent;
       this.user = user;
       this.date = date;
       this.price = price;
       this.restl = restl;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_student_id", nullable=false)
    public CourseStudent getCourseStudent() {
        return this.courseStudent;
    }
    
    public void setCourseStudent(CourseStudent courseStudent) {
        this.courseStudent = courseStudent;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_app_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="price", precision=22, scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="restl", length=10)
    public Date getRestl() {
        return this.restl;
    }
    
    public void setRestl(Date restl) {
        this.restl = restl;
    }




}


